# Generated by Django 4.1.1 on 2022-11-29 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_parishhubtimes'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Day', models.DateField()),
                ('Time', models.CharField(max_length=15)),
                ('Title', models.CharField(max_length=50)),
                ('Details', models.TextField()),
            ],
        ),
    ]
