# Generated by Django 4.1.1 on 2022-11-16 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MassTimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ChurchID', models.IntegerField()),
                ('Time', models.TextField()),
                ('Day', models.CharField(max_length=9)),
                ('Comment', models.TextField()),
            ],
        ),
    ]
