# Generated by Django 4.1.1 on 2022-11-27 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_priestmessage_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUsReturns',
            fields=[
                ('ContactID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.CharField(max_length=200)),
                ('Member', models.CharField(max_length=3)),
                ('Message', models.TextField()),
            ],
        ),
    ]
