# Generated by Django 4.1.1 on 2022-11-30 21:48

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0006_newsletterpdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='SacramentContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SacramentName', models.CharField(max_length=50)),
                ('SacramentDescription', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
