# Generated by Django 4.1.1 on 2022-11-30 21:55

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0007_sacramentcontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sacramentcontent',
            name='SacramentDescription',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
