# Generated by Django 4.1.1 on 2022-11-30 23:10

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0008_alter_sacramentcontent_sacramentdescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sacramentcontent',
            name='SacramentDescription',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text'),
        ),
    ]
