# Generated by Django 4.1.1 on 2022-12-02 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0009_alter_sacramentcontent_sacramentdescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clergyName', models.CharField(max_length=100)),
                ('clergyRole', models.CharField(max_length=50)),
                ('clergyDescription', models.TextField()),
                ('clergyPicture', models.ImageField(upload_to='')),
            ],
        ),
    ]
