# Generated by Django 4.1.1 on 2022-12-03 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0010_clergy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoolName', models.TextField()),
                ('schoolIcon', models.ImageField(upload_to='')),
                ('schoolDescription', models.TextField()),
                ('schoolPhone', models.CharField(max_length=12)),
                ('schoolFacebook', models.TextField()),
                ('schoolWebsite', models.TextField()),
            ],
        ),
    ]
