# Generated by Django 4.1.1 on 2022-12-10 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0015_alter_sacramentcontent_sacramentdescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaptismForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_surname', models.TextField()),
                ('child_dob', models.DateField()),
                ('child_baptism_name', models.TextField()),
                ('address', models.TextField()),
                ('postcode', models.CharField(max_length=8)),
                ('telephone_number', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('father_name', models.TextField()),
                ('father_dob', models.DateField()),
                ('father_religion', models.TextField()),
                ('father_baptised_in_parish', models.CharField(max_length=1)),
                ('father_date_baptism', models.DateField()),
                ('father_baptism_church', models.TextField()),
                ('father_date_confirmation', models.DateField()),
                ('father_confirmation_church', models.TextField()),
                ('mother_name', models.TextField()),
                ('mother_dob', models.DateField()),
                ('mother_religion', models.TextField()),
                ('mother_baptised_in_parish', models.CharField(max_length=1)),
                ('mother_date_baptism', models.DateField()),
                ('mother_baptism_church', models.TextField()),
                ('mother_date_confirmation', models.DateField()),
                ('mother_confirmation_church', models.TextField()),
                ('parents_marital_status', models.TextField()),
                ('godparent_name_1', models.TextField()),
                ('godparent_religion_1', models.TextField()),
                ('godparent_address_1', models.TextField()),
                ('godparent_postcode_1', models.CharField(max_length=7)),
                ('godparent_telephone_1', models.CharField(max_length=12)),
                ('godparent_dob_1', models.DateField()),
                ('godparent_baptism_church_1', models.TextField()),
                ('godparent_confirmation_date_1', models.DateField()),
                ('godparent_confirmation_church_1', models.TextField()),
                ('godparent_practicing_1', models.TextField()),
                ('godparent_name_2', models.TextField()),
                ('godparent_religion_2', models.TextField()),
                ('godparent_address_2', models.TextField()),
                ('godparent_postcode_2', models.CharField(max_length=7)),
                ('godparent_telephone_2', models.CharField(max_length=12)),
                ('godparent_dob_2', models.DateField()),
                ('godparent_baptism_church_2', models.TextField()),
                ('godparent_confirmation_date_2', models.DateField()),
                ('godparent_confirmation_church_2', models.TextField()),
                ('godparent_practicing_2', models.TextField()),
                ('cw_name', models.TextField()),
                ('cw_gender', models.CharField(max_length=1)),
                ('cw_religion', models.TextField()),
                ('cw_practicing', models.TextField()),
                ('first_child', models.CharField(max_length=1)),
                ('course_attended', models.CharField(max_length=1)),
                ('course_church', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ChildClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_name', models.TextField()),
                ('child_dob', models.DateField()),
                ('child_date_baptism', models.DateField()),
                ('child_school', models.TextField()),
                ('family_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.baptismform')),
            ],
        ),
    ]
