# Generated by Django 4.1.1 on 2022-12-10 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0016_baptismform_childclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='baptismform',
            name='cw_gender_2',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='baptismform',
            name='cw_name_2',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='baptismform',
            name='cw_practicing_2',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='baptismform',
            name='cw_religion_2',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='baptismform',
            name='mother_maidan_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='baptismform',
            name='postcode',
            field=models.CharField(max_length=7),
        ),
    ]
