# Generated by Django 4.1.1 on 2022-12-11 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0018_alter_baptismform_cw_gender_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baptismform',
            name='godparent_address_2',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='baptismform',
            name='godparent_baptism_church_2',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='baptismform',
            name='godparent_confirmation_church_2',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='baptismform',
            name='godparent_confirmation_date_2',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='baptismform',
            name='godparent_dob_2',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='baptismform',
            name='godparent_name_2',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='baptismform',
            name='godparent_postcode_2',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AlterField(
            model_name='baptismform',
            name='godparent_practicing_2',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='baptismform',
            name='godparent_religion_2',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='baptismform',
            name='godparent_telephone_2',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
