# Generated by Django 4.1.1 on 2022-12-12 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0019_alter_baptismform_godparent_address_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baptismform',
            name='practicing_church_time',
            field=models.TextField(default=''),
        ),
    ]
