# Generated by Django 4.1.1 on 2022-12-12 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0021_alter_baptismform_father_date_baptism_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baptismform',
            name='father_baptism_church',
            field=models.TextField(blank=True, default='None'),
        ),
        migrations.AlterField(
            model_name='baptismform',
            name='father_date_confirmation',
            field=models.DateField(blank=True, default='None'),
        ),
        migrations.AlterField(
            model_name='baptismform',
            name='mother_date_baptism',
            field=models.TextField(blank=True, default='None'),
        ),
        migrations.AlterField(
            model_name='baptismform',
            name='mother_date_confirmation',
            field=models.TextField(blank=True, default='None'),
        ),
        migrations.AlterField(
            model_name='childclass',
            name='child_date_baptism',
            field=models.TextField(blank=True, default='None'),
        ),
        migrations.AlterField(
            model_name='childclass',
            name='child_school',
            field=models.TextField(blank=True),
        ),
    ]
