# Generated by Django 4.1.1 on 2022-12-12 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0022_alter_baptismform_father_baptism_church_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baptismform',
            name='father_date_confirmation',
            field=models.TextField(blank=True, default='None'),
        ),
    ]
