# Generated by Django 4.1.1 on 2022-12-12 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0023_alter_baptismform_father_date_confirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baptismform',
            name='father_baptism_church',
            field=models.TextField(blank=True, default='None', null=True),
        ),
        migrations.AlterField(
            model_name='baptismform',
            name='father_date_baptism',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='baptismform',
            name='father_date_confirmation',
            field=models.TextField(blank=True, default='None', null=True),
        ),
        migrations.AlterField(
            model_name='baptismform',
            name='mother_baptism_church',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='baptismform',
            name='mother_confirmation_church',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='baptismform',
            name='mother_date_baptism',
            field=models.TextField(blank=True, default='None', null=True),
        ),
        migrations.AlterField(
            model_name='baptismform',
            name='mother_date_confirmation',
            field=models.TextField(blank=True, default='None', null=True),
        ),
    ]
