# Generated by Django 4.1.1 on 2022-12-12 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0024_alter_baptismform_father_baptism_church_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baptismform',
            name='godparent_confirmation_date_2',
            field=models.TextField(blank=True, default='None', null=True),
        ),
        migrations.AlterField(
            model_name='baptismform',
            name='godparent_dob_2',
            field=models.TextField(blank=True, default='None', null=True),
        ),
    ]
