# Generated by Django 4.1.1 on 2022-11-30 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_calendaritem'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsletter_pdf', models.FileField(upload_to='')),
            ],
        ),
    ]
